import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NavbarComponent from "@/components/navbar/Navbar";
import Login from "@/components/Login/Login";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Verifhire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
            <h1>Home</h1>
            <p>Welcome to the Next.js App!</p>
        </div>
      {/* <NavbarComponent/>
      <div className="d-flex justify-content-center align-items-center layout-container">
      <Login/>
      </div> */}
     
    </>
  );
}
